name: 01 - Firstworkflow
on: 
    #- push
    - workflow_dispatch
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Saludar
              run: echo 'Hello world'
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            # - name: Multilinea
            #   run: |
            #    echo "Fallo"
            #    exit 1
            - name: Paso Exitoso
              run: |
                echo "Exito"
                exit 0
            - name: Decir adios
              run: echo "adios"
            