name: 13 - Working with Outputs.
on:
    workflow_dispatch:
        inputs:
            build-status:
                description: 'Choose the build status for the demo'
                type: choice
                options: [success, failure]
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: print GITHUB_OUTPUT
              run: echo $GITHUB_OUTPUT
            - name: build
              id: build
              run: echo "status=${{inputs.build-status}}" >> $GITHUB_OUTPUT
        outputs:
            build-status: ${{steps.build.outputs.status}}
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{needs.build.outputs.build-status == 'success'}}
        steps:
            - name: Deploy
              run: echo "Deploying"