name: 18 - 2 - Reusable Workflows.
on:
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflows.yml
        with: 
            target_directory: "ejemplo"
    print-outputs:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Print outputs
              run: |
                echo "${{needs.deploy.outputs.build-status}}"
                echo "${{needs.deploy.outputs.url}}"
    

